CREATE TABLE [dbo].[Grade] (
    [CourseId] VARCHAR (30) NOT NULL,
    [CURP]     VARCHAR (30) NOT NULL,
    [Grade]    VARCHAR (5)  NOT NULL,
    CONSTRAINT [PK_GRADE] PRIMARY KEY CLUSTERED ([CourseId] ASC, [CURP] ASC),
    CONSTRAINT [FK_GRADE_STUDENT] FOREIGN KEY ([CURP]) REFERENCES [dbo].[Student] ([CURP]),
    CONSTRAINT [FK_GRADE_TEACHER] FOREIGN KEY ([CourseId]) REFERENCES [dbo].[Course] ([CourseId])
);

